name: riego
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  d_chart: ^2.9.1
  one_clock: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/.
   - assets/icons/.
   - assets/img/.